// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const CLEAR_ALERTS = 'CLEAR_ALERTS';

// Auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// SideMenu
export const SET_SIDE_MENU = 'SET_SIDE_MENU';

// Favour
export const FAVOURS_LOADING = 'FAVOURS_LOADING';
export const GET_FAVOURS = 'GET_FAVOURS';
export const GET_FAVOURS_FAILED = 'GET_FAVOURS_FAILED';
export const GET_CURRENT_FAVOUR = 'GET_CURRENT_FAVOUR';
export const GET_CURRENT_FAVOUR_FAILED = 'GET_CURRENT_FAVOUR_FAILED';
export const UNMOUNT_CURRENT_FAVOUR = 'UNMOUNT_CURRENT_FAVOUR';
export const CREATE_FAVOUR = 'CREATE_FAVOUR';

// Modal
export const SHOW_HIDE_MODAL = 'SHOW_HIDE_MODAL';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

// Requests
export const REQUESTS_LOADING = 'REQUESTS_LOADING';
export const GET_REQUESTS = 'GET_REQUESTS';
export const GET_REQUESTS_FAILED = 'GET_REQUESTS_FAILED';
export const UNMOUNT_REQUESTS = 'UNMOUNT_REQUESTS';
export const IS_REQUESTED = 'IS_REQUESTED';
export const SET_MY_REQUEST = 'SET_MY_REQUEST';
export const CHECK_PENDING_REQUESTS = 'CHECK_PENDING_REQUESTS';
export const CHECK_PENDING_REQUESTS_FAILED = 'CHECK_PENDING_REQUESTS_FAILED';